language: csharp
addons:
  apt:
    packages:
    - libdiscid-dev # libdiscid0-dev on trusty and later, but whitelisting that doesn't work
    - nunit-console
dist: precise
install:
  - nuget restore dotnet-discid.sln
script:
  - xbuild /p:Configuration=Release dotnet-discid.sln
  - nunit-console dotnet-discid-test/bin/Debug/DotNetDiscIdTest.dll
# env:
#   - LD_LIBRARY_PATH=/usr/lib/:/usr/lib/x86_64-linux-gnu/
