language: csharp
dist: xenial
addons:
  apt:
    packages:
    - libdiscid-dev
install:
  - nuget restore dotnet-discid.sln
  - nuget install NUnit.Console -Version 3.10.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release dotnet-discid.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.10.0/tools/nunit3-console.exe dotnet-discid-test/bin/Release/DotNetDiscIdTest.dll
  - msbuild /p:Configuration=Debug dotnet-discid.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.10.0/tools/nunit3-console.exe dotnet-discid-test/bin/Debug/DotNetDiscIdTest.dll
