language: csharp
addons:
  apt:
    packages:
    - nunit-console
sudo: required
install:
  - sudo apt-get install -qq libdiscid0-dev
  - nuget restore dotnet-discid.sln
script:
  - xbuild /p:Configuration=Release dotnet-discid.sln
  - nunit-console dotnet-discid-test/bin/Debug/DotNetDiscIdTest.dll
# env:
#   - LD_LIBRARY_PATH=/usr/lib/:/usr/lib/x86_64-linux-gnu/
