language: c
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq mono-devel mono-gmcs nunit-console libdiscid0
env:
  - LD_LIBRARY_PATH=/usr/lib/
  - MONO_LOG_LEVEL=debug
script:
  - xbuild
  - ls /usr/lib/libdiscid*
  - ls /usr/lib/libMonoPosixHelper*
  - nunit-console dotnet-discid-test/bin/Debug/dotnet-discid-test.dll