language: csharp
dist: xenial
addons:
  apt:
    packages:
    - nunit-console
    - libdiscid-dev
install:
  - nuget restore dotnet-discid.sln
script:
  - xbuild /p:Configuration=Debug   dotnet-discid.sln
  - xbuild /p:Configuration=Release dotnet-discid.sln
  - nunit-console -framework=4.0 dotnet-discid-test/bin/Release/DotNetDiscIdTest.dll
  - nunit-console -framework=4.0 dotnet-discid-test/bin/Debug/DotNetDiscIdTest.dll
